apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-api
  namespace: configmap-sync-test
  labels:
    app: mock-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-api
  template:
    metadata:
      labels:
        app: mock-api
    spec:
      containers:
      - name: mock-api
        image: kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mock-api
  namespace: configmap-sync-test
spec:
  selector:
    app: mock-api
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mock-api-response
  namespace: configmap-sync-test
data:
  response.json: |
    {
      "app": {
        "name": "test-application",
        "environment": "development"
      },
      "database": {
        "host": "db.example.com",
        "port": 5432,
        "name": "testdb"
      },
      "features": {
        "featureA": true,
        "featureB": false
      }
    }
