apiVersion: v1
kind: ConfigMap
metadata:
  name: mock-api-response
  namespace: configmap-sync-test
data:
  response.json: |
    {
      "app": {
        "name": "test-application",
        "environment": "development"
      },
      "database": {
        "host": "db.example.com",
        "port": 5432,
        "name": "testdb"
      },
      "features": {
        "featureA": true,
        "featureB": false
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-api
  namespace: configmap-sync-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-api
  template:
    metadata:
      labels:
        app: mock-api
    spec:
      containers:
      - name: mock-api
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: api-response
          mountPath: /usr/share/nginx/html/api/config
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: api-response
        configMap:
          name: mock-api-response
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: configmap-sync-test
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location /api/config {
            default_type application/json;
            add_header Content-Type application/json;
            alias /usr/share/nginx/html/api/config/response.json;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: mock-api
  namespace: configmap-sync-test
spec:
  selector:
    app: mock-api
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
