---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configmap-sync-operator
  namespace: configmap-sync-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmap-sync-operator
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["apiconfig.example.com"]
  resources: ["configmapsynchronizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apiconfig.example.com"]
  resources: ["configmapsynchronizers/status"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmap-sync-operator
subjects:
- kind: ServiceAccount
  name: configmap-sync-operator
  namespace: configmap-sync-test
roleRef:
  kind: ClusterRole
  name: configmap-sync-operator
  apiGroup: rbac.authorization.k8s.io
