apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: configmap-sync-test
type: Opaque
data:
  # These are sample credentials, in a real environment you would use properly base64-encoded values
  password: cGFzc3dvcmQxMjM=  # base64 encoded "password123"
  token: dGhpc2lzYXNhbXBsZXRva2VuCg==  # base64 encoded "thisisasampletoken"
