apiVersion: v1
kind: ConfigMap
metadata:
  name: test-template
  namespace: configmap-sync-test
data:
  # Basic configuration template for standard API data
  app-config.properties: |
    # API Configuration
    api.server.url={{ .ServerUrl | default "http://localhost:8080" }}
    api.server.port={{ .Port | default "8080" }}
    api.environment={{ .Environment | default "development" }}
    
    # Feature Flags
    {{ if .FeatureA }}
    feature.a.enabled=true
    {{ else }}
    feature.a.enabled=false
    {{ end }}
    
    # Default values for missing variables
    {{ if .MissingFeature }}
    missing.feature=enabled
    {{ else }}
    missing.feature=disabled
    {{ end }}
  
  # Template for secured API endpoints
  secure-api-config.yaml: |
    apiConfig:
      endpoint: {{ .ApiEndpoint | default "https://api.default.com" }}
      timeout: {{ .Timeout | default "30s" }}
      retries: 3
      features:
        {{- if .EnabledFeatures }}
        {{- range $index, $feature := .EnabledFeatures }}
        - enabled: {{ $feature }}
        {{- end }}
        {{- else }}
        - enabled: false
        {{- end }}
